import java.io.Serializable;

/**
 * Pulls data from Model and verifies the data
 * Serialization processed in this class
 * 
 * @author richardbankhead
 */
public class Controller implements Serializable{

	/** Auto generated by Eclipse. I haven't Serialized data before so just leaving this for now --RB*/
	private static final long serialVersionUID = 1L;

}
